### ISSUE TITLE
Accidentally pull in unrelated history from other repository

### ISSUE THREAD

**Issue by Aetf** [sma11black/hexo-action#7]
To populate the `.deploy_git` directory, the action currently is hardcoded to use `$GITHUB_ACTOR/$GITHUB_ACTOR.github.io` as the remote. This is not useable when setting up other github page repositories, such as an organization page.

Today I just accidentally pushed my personal website history to our organization website.

**Comment by sma11black** [comment]
You are right, the hardcoded way of using `github.actor` is indeed not accurate. Now I have modified it to get the owner account field of Github Pages repository from the **_config.yml** file.

I tested it on another personal account and it was successful. If you can test it on your organization account and success, I will publish a new release version.

To test this action, you need to temporarily modify your workflow file:
```yaml
...
- name: Deploy
  id: deploy
  uses: sma11black/hexo-action@master  # replace "v1.0.1" with "master" branch
...
```
